const client='sneaker-street_jazihe',scriptURL='https://mdeploy.andata.ru/i/_auto/sneaker-street_jazihe';if(typeof AndataTracking==='undefined'){class AndataTracking{constructor(){this.ubtcuid=null;this.l_ubtcuid=null;this.mphone_pagehit=null;}
static get client(){return client;}
static get scriptURL(){return scriptURL;}
static loadJS(src,callback){var s=document.createElement('script');s.src=src;s.async=true;s.onreadystatechange=s.onload=function(){var state=s.readyState;if(!callback.done&&(!state||/loaded|complete/.test(state))){callback.done=true;callback();}};document.getElementsByTagName('head')[0].appendChild(s);}
static loadFormsHandler(){}
static getContext(){return[{schema:'iglu:ru.andata/forms_pagehit_cuid/jsonschema/1-0-0',data:{ubtcuid:this.ubtcuid,last_ubtcuid:this.l_ubtcuid,}}];};}
var _ubtcuid=document.cookie.match(new RegExp("(?:^|; )"+'_ubtcuid'.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+"=([^;]*)"));_ubtcuid=_ubtcuid?_ubtcuid[1]:'';AndataTracking.l_ubtcuid=_ubtcuid;if(!!window.ubtcuid){AndataTracking.ubtcuid=window.ubtcuid;}else{var ccid='_'+Math.random().toString(36).substr(2,16);AndataTracking.ubtcuid=([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,c=function(с){return(c^crypto.getRandomValues(new Uint8Array(1))[0]&15>>c/4).toString(16)});window.ubtcuid=AndataTracking.ubtcuid;}
(function(g,l,o,b,a,i,d){if(!g[a]){g.GlobalAndataTrackingNamespace=g.GlobalAndataTrackingNamespace||[];g.GlobalAndataTrackingNamespace.push(a);g[a]=function(){(g[a].q=g[a].q||[]).push(arguments)};g[a].q=g[a].q||[];i=l.createElement(o);d=l.getElementsByTagName(o)[0];i.async=1;i.src=b;d.parentNode.insertBefore(i,d)}}(window,document,"script","//mdeploy.andata.ru/gt.min.js","globalid"));var collector='gt.andata.ru';window.globalid('newTracker','cf',collector,{appId:'sneaker-street_jazihe',platform:'web',contexts:{webPage:true,performanceTiming:true,gaCookies:true}});window.globalid('enableActivityTracking',2,5);window.globalid('enableLinkClickTracking');window.globalid('enableFormTracking',null,AndataTracking.getContext());window.globalid('trackPageView',null,AndataTracking.getContext());document.cookie="_ubtcuid="+AndataTracking.ubtcuid+"; path=/";(function(){j=document.createElement('script');j.async=true;j.src="https://lk.andata.ru/tag-manager/sneaker-street_jazihe";j2=document.getElementsByTagName('script')[0];j2.parentNode.insertBefore(j,j2)})()
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',handlerButtonsEvents);}else{handlerButtonsEvents();}
function handlerButtonsEvents(){var body=document.querySelector('body');body.addEventListener('click',function(e){if(!e.target.hasAttribute('data-andata-id'))
return false;var xhr=new XMLHttpRequest();xhr.addEventListener("readystatechange",function(){if(this.readyState===4){console.log(this.responseText);}});var api_key="0";var event_name="click_element_event";var event_source=location.host;var d={"button_id":e.target.getAttribute('data-andata-id'),"button_text":e.target.textContent.trim(),"tagname":e.target.tagName,"url":location.href};xhr.open("GET","https://mdeploy.andata.ru/api.php?apikey="+api_key+"&event_name="+event_name+"&event_source="+event_source+"&event_ubtcuid="+window.ubtcuid+"&event_data="+JSON.stringify(d));xhr.send();},true);}}else{console.log('Attempt to reinitialize Andata Tracking');}